name: Build

on:
  pull_request: {}
  push:
    branches:
      - integration

jobs:
  build:
    name: Build
    strategy:
      matrix:
        runners:
          - {
              system: aarch64-darwin,
              runner: "namespace-profile-mac-m2-12c28g",
            }
          - { system: aarch64-linux, runner: "UbuntuLatest32Cores128GArm" }
          - { system: x86_64-linux, runner: "namespace-profile-linuxamd32c64g-cache" }
    permissions:
      id-token: "write"
      contents: "read"
    runs-on: ${{ matrix.runners.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix flake check --system ${{ matrix.runners.system }}
  success:
    runs-on: ubuntu-latest
    needs:
      - build
    if: ${{ always() }}
    steps:
      - run: "true"
      - run: |
          echo "A dependent in the build matrix failed:"
          echo "$needs"
          exit 1
        env:
          needs: ${{ toJSON(needs) }}
        if: |
          contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'cancelled')
